$(VERBOSE).SILENT:

.PHONY: all
all:

.PHONY: pre-check
pre-check:
	touch typings/LSP/__init__.py

.PHONY: check
check:
	mypy -p plugin
	flake8 .
	black --check --diff .
	isort --check --diff .

.PHONY: post-check
post-check:
	rm -f typings/LSP/__init__.py
