from . import blend_modes as blend_modes, porter_duff as porter_duff
from ..channels import Channel as Channel
from ..color import Color as Color

def clip_channel(coord: float, channel: Channel) -> float: ...
def apply_compositing(color1: Color, color2: Color, blender: blend_modes.Blend | None, operator: str | bool) -> Color: ...
def compose(color: Color, backdrop: list['Color'], blend: str | bool = True, operator: str | bool = True, space: str | None = None) -> Color: ...
