from ..util import parseBoolValue as parseBoolValue
from _typeshed import Incomplete

class Extension:
    config: Incomplete
    def __init__(self, **kwargs) -> None: ...
    def getConfig(self, key, default: str = ''): ...
    def getConfigs(self): ...
    def getConfigInfo(self): ...
    def setConfig(self, key, value) -> None: ...
    def setConfigs(self, items) -> None: ...
    def extendMarkdown(self, md) -> None: ...
