from .constants import ST_PACKAGES_PATH as ST_PACKAGES_PATH
from typing import Any

log_debug: bool

def set_debug_logging(logging_enabled: bool) -> None: ...
def debug(*args: Any) -> None: ...
def trace() -> None: ...
def exception_log(message: str, ex: Exception) -> None: ...
def printf(*args: Any, prefix: str = 'LSP') -> None: ...
