from .protocol import DocumentUri as DocumentUri
from .sessions import Session as Session
from .views import parse_uri as parse_uri
from pathlib import Path
from typing import Iterable

def simple_path(session: Session | None, uri: DocumentUri) -> str: ...
def project_path(project_folders: Iterable[Path], file_path: Path) -> Path | None: ...
def simple_project_path(project_folders: Iterable[Path], file_path: Path) -> Path | None: ...
def resolve_simple_project_path(project_folders: Iterable[Path], file_path: Path) -> Path | None: ...
def project_base_dir(project_folders: Iterable[Path], file_path: Path) -> Path | None: ...
def split_project_path(project_folders: Iterable[Path], file_path: Path) -> tuple[Path, Path] | None: ...
