import socket
import subprocess
import threading
import weakref
from .constants import ST_PLATFORM as ST_PLATFORM
from .logging import debug as debug, exception_log as exception_log
from .types import TCP_CONNECT_TIMEOUT as TCP_CONNECT_TIMEOUT, TransportConfig as TransportConfig
from _typeshed import Incomplete
from typing import Any, Callable, Generic, IO, Protocol, TypeVar

T = TypeVar('T')
T_contra = TypeVar('T_contra', contravariant=True)

class StopLoopError(Exception): ...

class Transport(Generic[T]):
    def send(self, payload: T) -> None: ...
    def close(self) -> None: ...

class TransportCallbacks(Protocol[T_contra]):
    def on_transport_close(self, exit_code: int, exception: Exception | None) -> None: ...
    def on_payload(self, payload: T_contra) -> None: ...
    def on_stderr_message(self, message: str) -> None: ...

class AbstractProcessor(Generic[T]):
    def write_data(self, writer: IO[bytes], data: T) -> None: ...
    def read_data(self, reader: IO[bytes]) -> T | None: ...

class JsonRpcProcessor(AbstractProcessor[dict[str, Any]]):
    def write_data(self, writer: IO[bytes], data: dict[str, Any]) -> None: ...
    def read_data(self, reader: IO[bytes]) -> dict[str, Any] | None: ...
    @staticmethod
    def _encode(data: dict[str, Any]) -> bytes: ...
    @staticmethod
    def _decode(message: bytes) -> dict[str, Any]: ...

class ProcessTransport(Transport[T]):
    _closed: bool
    _process: Incomplete
    _socket: Incomplete
    _reader: Incomplete
    _writer: Incomplete
    _stderr: Incomplete
    _processor: Incomplete
    _reader_thread: Incomplete
    _writer_thread: Incomplete
    _callback_object: Incomplete
    _send_queue: Incomplete
    _stderr_thread: Incomplete
    def __init__(self, name: str, process: subprocess.Popen | None, socket: socket.socket | None, reader: IO[bytes], writer: IO[bytes], stderr: IO[bytes] | None, processor: AbstractProcessor[T], callback_object: TransportCallbacks[T]) -> None: ...
    def send(self, payload: T) -> None: ...
    def close(self) -> None: ...
    def _join_thread(self, t: threading.Thread) -> None: ...
    def __del__(self) -> None: ...
    def _read_loop(self) -> None: ...
    def _end(self, exception: Exception | None) -> None: ...
    def _write_loop(self) -> None: ...
    def _stderr_loop(self) -> None: ...

json_rpc_processor: Incomplete

def create_transport(config: TransportConfig, cwd: str | None, callback_object: TransportCallbacks) -> Transport[dict[str, Any]]: ...

_subprocesses: weakref.WeakSet[subprocess.Popen]

def kill_all_subprocesses() -> None: ...
def _fixup_startup_args(args: list[str]) -> Any: ...
def _start_subprocess(args: list[str], stdin: int, stdout: int, stderr: int, startupinfo: Any, env: dict[str, str], cwd: str | None) -> subprocess.Popen: ...
def _await_client_connection(listener_socket: socket.socket) -> tuple[socket.socket, IO[bytes], IO[bytes]]: ...
def _start_subprocess_and_await_connection(listener_socket: socket.socket, subprocess_starter: Callable[[], subprocess.Popen]) -> tuple[subprocess.Popen, socket.socket, IO[bytes], IO[bytes]]: ...
def _connect_tcp(port: int) -> socket.socket | None: ...
