import sublime
from .constants import ST_INSTALLED_PACKAGES_PATH as ST_INSTALLED_PACKAGES_PATH, ST_PACKAGES_PATH as ST_PACKAGES_PATH
from typing import Any

def filename_to_uri(file_name: str) -> str: ...
def view_to_uri(view: sublime.View) -> str: ...
def uri_to_filename(uri: str) -> str: ...
def parse_uri(uri: str) -> tuple[str, str]: ...
def unparse_uri(parsed_uri: tuple[str, str]) -> str: ...
def _to_resource_uri(path: str, prefix: str) -> str: ...
def _uppercase_driveletter(match: Any) -> str: ...
