from .events import *
from .nodes import *
from .error import MarkedYAMLError
from _typeshed import Incomplete

__all__ = ['Composer', 'ComposerError']

class ComposerError(MarkedYAMLError): ...

class Composer:
    anchors: Incomplete
    def __init__(self) -> None: ...
    def check_node(self): ...
    def get_node(self): ...
    def get_single_node(self): ...
    def compose_document(self): ...
    def compose_node(self, parent, index): ...
    def compose_scalar_node(self, anchor): ...
    def compose_sequence_node(self, anchor): ...
    def compose_mapping_node(self, anchor): ...
