from _typeshed import Incomplete

__all__ = ['lex', 'format', 'highlight']

def lex(code, lexer): ...
def format(tokens, formatter, outfile: Incomplete | None = None): ...
def highlight(code, lexer, formatter, outfile: Incomplete | None = None): ...
