from _typeshed import Incomplete
from collections.abc import Generator

def apply_filters(stream, filters, lexer: Incomplete | None = None): ...
def simplefilter(f): ...

class Filter:
    options: Incomplete
    def __init__(self, **options) -> None: ...
    def filter(self, lexer, stream) -> None: ...

class FunctionFilter(Filter):
    function: Incomplete
    def __init__(self, **options) -> None: ...
    def filter(self, lexer, stream) -> Generator[Incomplete]: ...
