from _typeshed import Incomplete
from collections.abc import Generator

LEXER_ENTRY_POINT: str
FORMATTER_ENTRY_POINT: str
STYLE_ENTRY_POINT: str
FILTER_ENTRY_POINT: str

def find_plugin_lexers() -> Generator[Incomplete]: ...
def find_plugin_formatters() -> Generator[Incomplete]: ...
def find_plugin_styles() -> Generator[Incomplete]: ...
def find_plugin_filters() -> Generator[Incomplete]: ...
