from .token import STANDARD_TYPES as STANDARD_TYPES, Token as Token
from .util import add_metaclass as add_metaclass
from _typeshed import Incomplete

class StyleMeta(type):
    def __new__(mcs, name, bases, dct): ...
    def style_for_token(cls, token): ...
    def list_styles(cls): ...
    def styles_token(cls, ttype): ...
    def __iter__(cls): ...
    def __len__(cls) -> int: ...

class Style:
    background_color: str
    highlight_color: str
    styles: Incomplete
