from .comments import Comments as Comments
from _typeshed import Incomplete

JSON_PATTERN: Incomplete

def strip_dangling_commas(text, preserve_lines: bool = False): ...
def strip_comments(text, preserve_lines: bool = False): ...
def sanitize_json(text, preserve_lines: bool = False): ...
