import sublime
from typing import Callable

def show_popup(view: sublime.View, content: str, md: bool = True, css: str | None = None, flags: int = 0, location: int = -1, max_width: int = 320, max_height: int = 240, on_navigate: Callable | None = None, on_hide: Callable | None = None, wrapper_class: str | None = None, template_vars: dict | None = None, template_env_options: dict | None = None, nl2br: bool = True, allow_code_wrap: bool = False) -> None: ...
def update_popup(view: sublime.View, content: str, md: bool = True, css: str | None = None, wrapper_class: str | None = None, template_vars: str | None = None, nl2br: bool = True, allow_code_wrap: bool = False) -> None: ...
def format_frontmatter(values: dict) -> str: ...
def md2html(view: sublime.View, content: str, template_vars: str | None = None, template_env_options: dict | None = None, nl2br: bool = True, allow_code_wrap: bool = False) -> str: ...
def new_html_sheet(window: sublime.Window, name: str, contents: str, md: bool = True, css: str | None = None, flags: int = 0, group: int = -1, wrapper_class: str | None = None, template_vars: str | None = None, template_env_options: dict | None = None, nl2br: bool = True, allow_code_wrap: bool = False) -> sublime.HtmlSheet: ...
def update_html_sheet(sheet: sublime.HtmlSheet, contents: str, md: bool = True, css: str | None = None, wrapper_class: str | None = None, template_vars: str | None = None, template_env_options: dict | None = None, nl2br: bool = True, allow_code_wrap: bool = False) -> None: ...
def scope2style(view: sublime.View, scope: str, selected: bool = False, explicit_background: bool = False) -> str: ...
def worker_thread_resolver(url: str, done: Callable[[bytes], None]) -> None: ...
def resolve_images(minihtml: str, resolver: Callable[[str, Callable[[bytes], None]], None], on_done: Callable[[str], None]) -> object | None: ...
