import argparse
from _typeshed import Incomplete

PACKAGE_PATH: Incomplete
MESSAGE_DIR: str
MESSAGE_PATH: Incomplete
CONFIGURATION: Incomplete
RELEASE_BRANCH: Incomplete
GITHUB_REPO: Incomplete
RELEASE_VERSION_PREFIX: Incomplete
SETTINGS: Incomplete
PYTHON_VERSION_PATH: Incomplete

def get_message(fname: str) -> str: ...
def put_message(fname: str, text: str) -> None: ...
def build_messages_json(version_history: list[str]) -> None: ...
def version_history() -> list[str]: ...
def parse_version(version: str) -> tuple[int, int, int]: ...
def get_version_with_prefix(version: str) -> str: ...
def git(*args: str) -> str | None: ...
def commit_release(version: str) -> None: ...
def build_release(args: argparse.Namespace) -> None: ...
def publish_release(args: argparse.Namespace) -> None: ...
