from LSP.plugin.core.collections import DottedDict
from typing import Any
from unittest import TestCase

class DottedDictTests(TestCase):
    def verify(self, d: DottedDict, path: str, value: Any) -> None: ...
    def test_set_and_get(self) -> None: ...
    def test_remove(self) -> None: ...
    def test_assign(self) -> None: ...
    def test_update(self) -> None: ...
    def test_as_dict(self) -> None: ...
    def test_dunder_bool(self) -> None: ...
    def test_copy_whole(self) -> None: ...
    def test_copy_partial(self) -> None: ...
    def test_update_empty_dict(self) -> None: ...
    def test_from_base_and_override(self) -> None: ...
    def test_update_with_dicts(self) -> None: ...
