from LSP.plugin.core.sessions import SessionBufferProtocol as SessionBufferProtocol
from LSP.plugin.core.types import ClientConfig
from _typeshed import Incomplete
from setup import TextDocumentTestCase
from typing import Any, Generator

def get_auto_complete_trigger(sb: SessionBufferProtocol) -> list[dict[str, str]] | None: ...
def verify(testcase: TextDocumentTestCase, method: str, input_params: Any, expected_output_params: Any) -> Generator: ...

class ServerRequests(TextDocumentTestCase):
    def test_unknown_method(self) -> Generator: ...
    maxDiff: Incomplete
    def test_m_workspace_workspaceFolders(self) -> Generator: ...
    def test_m_workspace_configuration(self) -> Generator: ...
    def test_m_workspace_applyEdit(self) -> Generator: ...
    def test_m_workspace_applyEdit_with_nontrivial_promises(self) -> Generator: ...
    def test_m_client_registerCapability(self) -> Generator: ...
    def test_m_client_unregisterCapability(self) -> Generator: ...

class ServerRequestsWithAutoCompleteSelector(TextDocumentTestCase):
    @classmethod
    def get_stdio_test_config(cls) -> ClientConfig: ...
    def test_m_client_registerCapability(self) -> Generator: ...
