import unittest

class SortedWorkspaceFoldersTest(unittest.TestCase):
    def test_get_workspace_from_multi_folder_project(self) -> None: ...
    def test_longest_prefix(self) -> None: ...

class WorkspaceFolderTest(unittest.TestCase):
    def test_workspace_str(self) -> None: ...
    def test_workspace_repr(self) -> None: ...
    def test_workspace_to_dict(self) -> None: ...

class IsSubpathOfTest(unittest.TestCase):
    def is_subpath_case_differs(self) -> None: ...
