import unittest

class WindowsTests(unittest.TestCase):
    def test_converts_path_to_uri(self) -> None: ...
    def test_converts_uri_to_path(self) -> None: ...
    def test_converts_encoded_bad_drive_uri_to_path(self) -> None: ...
    def test_view_to_uri_with_valid_filename(self) -> None: ...
    def test_unc_path(self) -> None: ...
    def test_wsl_path(self) -> None: ...

class NixTests(unittest.TestCase):
    def test_converts_path_to_uri(self) -> None: ...
    def test_converts_uri_to_path(self) -> None: ...
    def test_view_to_uri_with_valid_filename(self) -> None: ...

class MultiplatformTests(unittest.TestCase):
    def test_resource_path(self) -> None: ...
    def test_buffer_uri(self) -> None: ...
    def test_parse_uri(self) -> None: ...
