import sublime
import unittest
from _typeshed import Incomplete

class TestDiff(unittest.TestCase):
    def test_add(self) -> None: ...
    def test_remove(self) -> None: ...
    def test_add_and_remove(self) -> None: ...
    def test_with_sets(self) -> None: ...
    def test_with_more_sets(self) -> None: ...
    def test_completely_new(self) -> None: ...

class TestDocumentSelector(unittest.TestCase):
    _opened_views: Incomplete
    def setUp(self) -> None: ...
    def tearDown(self) -> None: ...
    def _make_view(self, syntax: str, file_name: str) -> sublime.View: ...
    def test_language(self) -> None: ...
    def test_pattern_basics(self) -> None: ...
    def _make_html_view(self, file_name: str) -> sublime.View: ...
    def test_pattern_asterisk(self) -> None: ...
    def test_pattern_optional(self) -> None: ...
    def test_pattern_globstar(self) -> None: ...
    def test_pattern_grouping(self) -> None: ...
    def test_pattern_character_range(self) -> None: ...
    def test_pattern_negated_character_range(self) -> None: ...
    def test_base_scope_to_language_id_mappings(self) -> None: ...
