import unittest

class LspRenamePanelTests(unittest.TestCase):
    def test_utf16_ascii(self) -> None: ...
    def test_utf16_deseret_letter(self) -> None: ...
    def test_utf16_emoji(self) -> None: ...
    def test_utf16_emoji_zwj_sequence(self) -> None: ...
