import unittest
from LSP.plugin.core.protocol import TextDocumentEdit as TextDocumentEdit, TextEdit as TextEdit, WorkspaceEdit as WorkspaceEdit
from _typeshed import Incomplete
from setup import TextDocumentTestCase

FILENAME: Incomplete
URI: Incomplete
LSP_TEXT_EDIT: TextEdit
LSP_EDIT_CHANGES: WorkspaceEdit
LSP_TEXT_DOCUMENT_EDIT: TextDocumentEdit
LSP_EDIT_DOCUMENT_CHANGES: WorkspaceEdit
LSP_EDIT_DOCUMENT_CHANGES_2: WorkspaceEdit
LSP_EDIT_DOCUMENT_CHANGES_3: WorkspaceEdit

class TextEditTests(unittest.TestCase):
    def test_parse_from_lsp(self) -> None: ...

class WorkspaceEditTests(unittest.TestCase):
    def test_parse_no_changes_from_lsp(self) -> None: ...
    def test_parse_changes_from_lsp(self) -> None: ...
    def test_parse_document_changes_from_lsp(self) -> None: ...
    def test_no_clobbering_of_previous_edits(self) -> None: ...
    def test_prefers_document_edits_over_changes(self) -> None: ...

class SortByApplicationOrderTests(unittest.TestCase):
    def test_empty_sort(self) -> None: ...
    def test_sorts_in_application_order(self) -> None: ...
    def test_sorts_in_application_order2(self) -> None: ...

class ApplyDocumentEditTestCase(TextDocumentTestCase):
    def test_applies_text_edit(self) -> None: ...
    def test_applies_text_edit_with_placeholder(self) -> None: ...
    def test_applies_multiple_text_edits_with_placeholders(self) -> None: ...

class TemporarySetting(unittest.TestCase):
    def test_basics(self) -> None: ...
