from _typeshed import Incomplete
from unittesting import DeferrableTestCase

test_file_path: Incomplete

class ConfigParsingTests(DeferrableTestCase):
    def test_can_parse_old_client_settings(self) -> None: ...
    def test_can_parse_client_settings_with_languages(self) -> None: ...
    def test_can_parse_settings_with_selector(self) -> None: ...
    def test_can_update_config(self) -> None: ...
    def test_can_read_experimental_capabilities(self) -> None: ...
    def test_transport_config_extends_env_path(self) -> None: ...
    def test_list_in_environment(self) -> None: ...
    def test_disabled_capabilities(self) -> None: ...
    def test_filter_out_disabled_capabilities_ignore_partially(self) -> None: ...
    def test_path_maps(self) -> None: ...
