from unittest import TestCase
from unittesting import ViewTestCase

class GlobalConfigManagerTests(TestCase):
    def test_empty_configs(self) -> None: ...
    def test_global_config(self) -> None: ...
    def test_override_config(self) -> None: ...

class WindowConfigManagerTests(ViewTestCase):
    def test_no_configs(self) -> None: ...
    def test_with_single_config(self) -> None: ...
    def test_applies_project_settings(self) -> None: ...
    def test_disables_temporarily(self) -> None: ...
