from LSP.plugin.core.protocol import Diagnostic as Diagnostic
from LSP.plugin.core.types import Any as Any
from _typeshed import Incomplete
from unittesting import DeferrableTestCase

class ViewsTest(DeferrableTestCase):
    view: Incomplete
    mock_file_name: Incomplete
    def setUp(self) -> None: ...
    def tearDown(self) -> None: ...
    def test_missing_uri(self) -> None: ...
    def test_nonmissing_uri(self) -> None: ...
    def test_did_open(self) -> None: ...
    def test_did_change_full(self) -> None: ...
    def test_will_save(self) -> None: ...
    def test_will_save_wait_until(self) -> None: ...
    def test_did_save(self) -> None: ...
    def test_text_document_position_params(self) -> None: ...
    def test_text_document_formatting(self) -> None: ...
    def test_text_document_range_formatting(self) -> None: ...
    def test_point_to_offset(self) -> None: ...
    def test_point_to_offset_utf16(self) -> None: ...
    def test_selection_range_params(self) -> None: ...
    def test_minihtml_no_allowed_formats(self) -> None: ...
    def test_minihtml_conflicting_formats(self) -> None: ...
    def test_minihtml_format_string(self) -> None: ...
    def test_minihtml_format_marked_string(self) -> None: ...
    def test_minihtml_format_markup_content(self) -> None: ...
    def test_minihtml_handles_markup_content_plaintext(self) -> None: ...
    def test_minihtml_handles_marked_string(self) -> None: ...
    def test_minihtml_handles_marked_string_mutiple_spaces(self) -> None: ...
    def test_minihtml_handles_marked_string_array(self) -> None: ...
    def test_minihtml_ignores_non_allowed_string(self) -> None: ...
    def test_minihtml_ignores_non_allowed_marked_string(self) -> None: ...
    def test_minihtml_ignores_non_allowed_marked_string_array(self) -> None: ...
    def test_minihtml_ignores_non_allowed_markup_content(self) -> None: ...
    def test_minihtml_magiclinks(self) -> None: ...
    def _strip_style_attributes(self, content: str) -> str: ...
    def test_text2html_replaces_tabs_with_br(self) -> None: ...
    def test_text2html_non_breaking_space_and_control_char_with_entity(self) -> None: ...
    def test_text2html_replaces_two_or_more_spaces_with_nbsp(self) -> None: ...
    def test_text2html_does_not_replace_one_space_with_nbsp(self) -> None: ...
    def test_text2html_replaces_newlines_with_br(self) -> None: ...
    def test_text2html_parses_link_simple(self) -> None: ...
    def test_text2html_parses_link_in_angle_brackets(self) -> None: ...
    def test_text2html_parses_link_in_double_quotes(self) -> None: ...
    def test_text2html_parses_link_in_single_quotes(self) -> None: ...
    def test_lsp_color_to_phantom(self) -> None: ...
    def test_document_color_params(self) -> None: ...
    def test_text_document_code_action_params(self) -> None: ...
    def test_format_diagnostic_for_html(self) -> None: ...
    def test_escaped_newline_in_markdown(self) -> None: ...
    def test_single_backslash_in_markdown(self) -> None: ...
