from _typeshed import Incomplete
from unittesting import DeferrableTestCase

class LspServerPanelTests(DeferrableTestCase):
    window: Incomplete
    wm: Incomplete
    view: Incomplete
    panel: Incomplete
    def setUp(self) -> None: ...
    def assert_total_lines_equal(self, expected_total_lines) -> None: ...
    def update_panel(self, msg: str) -> None: ...
    def test_server_panel_circular_behavior(self) -> None: ...
