import sublime_plugin
from .core.registry import windows as windows
from .core.settings import client_configs as client_configs
from .core.windows import WindowManager as WindowManager
from _typeshed import Incomplete

class LspEnableLanguageServerGloballyCommand(sublime_plugin.WindowCommand):
    _items: Incomplete
    def run(self) -> None: ...
    def _on_done(self, index: int) -> None: ...

class LspEnableLanguageServerInProjectCommand(sublime_plugin.WindowCommand):
    _items: Incomplete
    def run(self) -> None: ...
    def _on_done(self, wm: WindowManager, index: int) -> None: ...

class LspDisableLanguageServerGloballyCommand(sublime_plugin.WindowCommand):
    _items: Incomplete
    def run(self) -> None: ...
    def _on_done(self, index: int) -> None: ...

class LspDisableLanguageServerInProjectCommand(sublime_plugin.WindowCommand):
    _items: Incomplete
    def run(self) -> None: ...
    def _on_done(self, wm: WindowManager, index: int) -> None: ...
