import sublime
from .core.protocol import FoldingRange as FoldingRange, FoldingRangeKind as FoldingRangeKind, FoldingRangeParams as FoldingRangeParams, Range as Range, Request as Request, UINT_MAX as UINT_MAX
from .core.registry import LspTextCommand as LspTextCommand
from .core.views import range_to_region as range_to_region, text_document_identifier as text_document_identifier

def folding_range_to_range(folding_range: FoldingRange) -> Range: ...
def sorted_folding_ranges(folding_ranges: list[FoldingRange]) -> list[FoldingRange]: ...

class LspFoldCommand(LspTextCommand):
    capability: str
    folding_ranges: list[FoldingRange]
    change_count: int
    folding_region: sublime.Region | None
    def is_visible(self, prefetch: bool = False, hidden: bool = False, strict: bool = True, event: dict | None = None, point: int | None = None) -> bool: ...
    def _handle_response_async(self, change_count: int, response: list[FoldingRange] | None) -> None: ...
    def description(self, prefetch: bool = False, hidden: bool = False, strict: bool = True, event: dict | None = None, point: int | None = None) -> str: ...
    def run(self, edit: sublime.Edit, prefetch: bool = False, hidden: bool = False, strict: bool = True, event: dict | None = None, point: int | None = None) -> None: ...
    def _handle_response_manual_async(self, point: int, strict: bool, response: list[FoldingRange] | None) -> None: ...

class LspFoldAllCommand(LspTextCommand):
    capability: str
    def run(self, edit: sublime.Edit, kind: str | None = None, event: dict | None = None) -> None: ...
    def _handle_response_async(self, kind: str | None, response: list[FoldingRange] | None) -> None: ...
