import sublime
from .core.constants import RegionKey as RegionKey
from .core.protocol import Location as Location, Point as Point, Request as Request
from .core.registry import LspTextCommand as LspTextCommand, get_position as get_position, windows as windows
from .core.sessions import Session as Session
from .core.settings import userprefs as userprefs
from .core.types import ClientConfig as ClientConfig
from .core.views import get_line as get_line, get_symbol_kind_from_scope as get_symbol_kind_from_scope, get_uri_and_position_from_location as get_uri_and_position_from_location, position_to_offset as position_to_offset, text_document_position_params as text_document_position_params
from .locationpicker import LocationPicker as LocationPicker
from _typeshed import Incomplete

OutputMode: Incomplete

class LspSymbolReferencesCommand(LspTextCommand):
    capability: str
    def is_enabled(self, event: dict | None = None, point: int | None = None, side_by_side: bool = False, force_group: bool = True, fallback: bool = False, group: int = -1, include_declaration: bool = False, output_mode: OutputMode | None = None) -> bool: ...
    def is_visible(self, event: dict | None = None, point: int | None = None, side_by_side: bool = False, force_group: bool = True, fallback: bool = False, group: int = -1, include_declaration: bool = False, output_mode: OutputMode | None = None) -> bool: ...
    def run(self, _: sublime.Edit, event: dict | None = None, point: int | None = None, side_by_side: bool = False, force_group: bool = True, fallback: bool = False, group: int = -1, include_declaration: bool = False, output_mode: OutputMode | None = None) -> None: ...
    def _handle_response_async(self, word: str, session: Session, side_by_side: bool, force_group: bool, fallback: bool, group: int, output_mode: OutputMode | None, event: dict | None, position: int, response: list[Location] | None) -> None: ...
    def _handle_response(self, word: str, session: Session, side_by_side: bool, force_group: bool, fallback: bool, group: int, output_mode: OutputMode | None, event: dict | None, position: int, response: list[Location] | None) -> None: ...
    def _handle_no_results(self, fallback: bool = False, side_by_side: bool = False) -> None: ...
    def _show_references_in_quick_panel(self, word: str, session: Session, locations: list[Location], side_by_side: bool, force_group: bool, group: int, position: int) -> None: ...
    def _show_references_in_output_panel(self, word: str, session: Session, locations: list[Location]) -> None: ...

def _get_relative_path(base_dir: str | None, file_path: str) -> str: ...
def _group_locations_by_uri(window: sublime.Window, config: ClientConfig, locations: list[Location]) -> dict[str, list[tuple[Point, str]]]: ...
