from . import util as util
from .blockparser import BlockParser as BlockParser
from _typeshed import Incomplete

logger: Incomplete

def build_block_parser(md, **kwargs): ...

class BlockProcessor:
    parser: Incomplete
    tab_length: Incomplete
    def __init__(self, parser) -> None: ...
    def lastChild(self, parent): ...
    def detab(self, text): ...
    def looseDetab(self, text, level: int = 1): ...
    def test(self, parent, block) -> None: ...
    def run(self, parent, blocks) -> None: ...

class ListIndentProcessor(BlockProcessor):
    ITEM_TYPES: Incomplete
    LIST_TYPES: Incomplete
    INDENT_RE: Incomplete
    def __init__(self, *args) -> None: ...
    def test(self, parent, block): ...
    def run(self, parent, blocks) -> None: ...
    def create_item(self, parent, block) -> None: ...
    def get_level(self, parent, block): ...

class CodeBlockProcessor(BlockProcessor):
    def test(self, parent, block): ...
    def run(self, parent, blocks) -> None: ...

class BlockQuoteProcessor(BlockProcessor):
    RE: Incomplete
    def test(self, parent, block): ...
    def run(self, parent, blocks) -> None: ...
    def clean(self, line): ...

class OListProcessor(BlockProcessor):
    TAG: str
    STARTSWITH: str
    LAZY_OL: bool
    SIBLING_TAGS: Incomplete
    RE: Incomplete
    CHILD_RE: Incomplete
    INDENT_RE: Incomplete
    def __init__(self, parser) -> None: ...
    def test(self, parent, block): ...
    def run(self, parent, blocks) -> None: ...
    def get_items(self, block): ...

class UListProcessor(OListProcessor):
    TAG: str
    RE: Incomplete
    def __init__(self, parser) -> None: ...

class HashHeaderProcessor(BlockProcessor):
    RE: Incomplete
    def test(self, parent, block): ...
    def run(self, parent, blocks) -> None: ...

class SetextHeaderProcessor(BlockProcessor):
    RE: Incomplete
    def test(self, parent, block): ...
    def run(self, parent, blocks) -> None: ...

class HRProcessor(BlockProcessor):
    RE: str
    SEARCH_RE: Incomplete
    match: Incomplete
    def test(self, parent, block): ...
    def run(self, parent, blocks) -> None: ...

class EmptyBlockProcessor(BlockProcessor):
    def test(self, parent, block): ...
    def run(self, parent, blocks) -> None: ...

class ParagraphProcessor(BlockProcessor):
    def test(self, parent, block): ...
    def run(self, parent, blocks) -> None: ...
