from . import util as util
from _typeshed import Incomplete

class State(list):
    def set(self, state) -> None: ...
    def reset(self) -> None: ...
    def isstate(self, state): ...

class BlockParser:
    blockprocessors: Incomplete
    state: Incomplete
    md: Incomplete
    def __init__(self, md) -> None: ...
    @property
    def markdown(self): ...
    root: Incomplete
    def parseDocument(self, lines): ...
    def parseChunk(self, parent, text) -> None: ...
    def parseBlocks(self, parent, blocks) -> None: ...
