from . import util as util
from _typeshed import Incomplete
from typing import NamedTuple

def build_inlinepatterns(md, **kwargs): ...

NOIMG: str
BACKTICK_RE: str
ESCAPE_RE: str
EMPHASIS_RE: str
STRONG_RE: str
SMART_STRONG_RE: str
SMART_EMPHASIS_RE: str
SMART_STRONG_EM_RE: str
EM_STRONG_RE: str
EM_STRONG2_RE: str
STRONG_EM_RE: str
STRONG_EM2_RE: str
STRONG_EM3_RE: str
LINK_RE: Incomplete
IMAGE_LINK_RE: str
REFERENCE_RE = LINK_RE
IMAGE_REFERENCE_RE = IMAGE_LINK_RE
NOT_STRONG_RE: str
AUTOLINK_RE: str
AUTOMAIL_RE: str
HTML_RE: str
ENTITY_RE: str
LINE_BREAK_RE: str

def dequote(string): ...

class EmStrongItem(NamedTuple('EmStrongItem', [('pattern', Incomplete), ('builder', Incomplete), ('tags', Incomplete)])): ...

class Pattern:
    ANCESTOR_EXCLUDES: Incomplete
    pattern: Incomplete
    compiled_re: Incomplete
    md: Incomplete
    def __init__(self, pattern, md: Incomplete | None = None) -> None: ...
    @property
    def markdown(self): ...
    def getCompiledRegExp(self): ...
    def handleMatch(self, m) -> None: ...
    def type(self): ...
    def unescape(self, text): ...

class InlineProcessor(Pattern):
    pattern: Incomplete
    compiled_re: Incomplete
    safe_mode: bool
    md: Incomplete
    def __init__(self, pattern, md: Incomplete | None = None) -> None: ...
    def handleMatch(self, m, data) -> None: ...

class SimpleTextPattern(Pattern):
    def handleMatch(self, m): ...

class SimpleTextInlineProcessor(InlineProcessor):
    def handleMatch(self, m, data): ...

class EscapeInlineProcessor(InlineProcessor):
    def handleMatch(self, m, data): ...

class SimpleTagPattern(Pattern):
    tag: Incomplete
    def __init__(self, pattern, tag) -> None: ...
    def handleMatch(self, m): ...

class SimpleTagInlineProcessor(InlineProcessor):
    tag: Incomplete
    def __init__(self, pattern, tag) -> None: ...
    def handleMatch(self, m, data): ...

class SubstituteTagPattern(SimpleTagPattern):
    def handleMatch(self, m): ...

class SubstituteTagInlineProcessor(SimpleTagInlineProcessor):
    def handleMatch(self, m, data): ...

class BacktickInlineProcessor(InlineProcessor):
    ESCAPED_BSLASH: Incomplete
    tag: str
    def __init__(self, pattern) -> None: ...
    def handleMatch(self, m, data): ...

class DoubleTagPattern(SimpleTagPattern):
    def handleMatch(self, m): ...

class DoubleTagInlineProcessor(SimpleTagInlineProcessor):
    def handleMatch(self, m, data): ...

class HtmlInlineProcessor(InlineProcessor):
    def handleMatch(self, m, data): ...
    def unescape(self, text): ...

class AsteriskProcessor(InlineProcessor):
    PATTERNS: Incomplete
    def build_single(self, m, tag, idx): ...
    def build_double(self, m, tags, idx): ...
    def build_double2(self, m, tags, idx): ...
    def parse_sub_patterns(self, data, parent, last, idx) -> None: ...
    def build_element(self, m, builder, tags, index): ...
    def handleMatch(self, m, data): ...

class UnderscoreProcessor(AsteriskProcessor):
    PATTERNS: Incomplete

class LinkInlineProcessor(InlineProcessor):
    RE_LINK: Incomplete
    RE_TITLE_CLEAN: Incomplete
    def handleMatch(self, m, data): ...
    def getLink(self, data, index): ...
    def getText(self, data, index): ...

class ImageInlineProcessor(LinkInlineProcessor):
    def handleMatch(self, m, data): ...

class ReferenceInlineProcessor(LinkInlineProcessor):
    NEWLINE_CLEANUP_RE: Incomplete
    RE_LINK: Incomplete
    def handleMatch(self, m, data): ...
    def evalId(self, data, index, text): ...
    def makeTag(self, href, title, text): ...

class ShortReferenceInlineProcessor(ReferenceInlineProcessor):
    def evalId(self, data, index, text): ...

class ImageReferenceInlineProcessor(ReferenceInlineProcessor):
    def makeTag(self, href, title, text): ...

class AutolinkInlineProcessor(InlineProcessor):
    def handleMatch(self, m, data): ...

class AutomailInlineProcessor(InlineProcessor):
    def handleMatch(self, m, data): ...
