from . import inlinepatterns as inlinepatterns, util as util
from _typeshed import Incomplete

def build_treeprocessors(md, **kwargs): ...
def isString(s): ...

class Treeprocessor(util.Processor):
    def run(self, root) -> None: ...

class InlineProcessor(Treeprocessor):
    md: Incomplete
    inlinePatterns: Incomplete
    ancestors: Incomplete
    def __init__(self, md) -> None: ...
    @property
    def markdown(self): ...
    stashed_nodes: Incomplete
    parent_map: Incomplete
    def run(self, tree, ancestors: Incomplete | None = None): ...

class PrettifyTreeprocessor(Treeprocessor):
    def run(self, root) -> None: ...
