from . import nodes as nodes
from ._compat import iteritems as iteritems, string_types as string_types, with_metaclass as with_metaclass
from .defaults import BLOCK_END_STRING as BLOCK_END_STRING, BLOCK_START_STRING as BLOCK_START_STRING, COMMENT_END_STRING as COMMENT_END_STRING, COMMENT_START_STRING as COMMENT_START_STRING, KEEP_TRAILING_NEWLINE as KEEP_TRAILING_NEWLINE, LINE_COMMENT_PREFIX as LINE_COMMENT_PREFIX, LINE_STATEMENT_PREFIX as LINE_STATEMENT_PREFIX, LSTRIP_BLOCKS as LSTRIP_BLOCKS, NEWLINE_SEQUENCE as NEWLINE_SEQUENCE, TRIM_BLOCKS as TRIM_BLOCKS, VARIABLE_END_STRING as VARIABLE_END_STRING, VARIABLE_START_STRING as VARIABLE_START_STRING
from .environment import Environment as Environment
from .exceptions import TemplateAssertionError as TemplateAssertionError, TemplateSyntaxError as TemplateSyntaxError
from .runtime import concat as concat
from .utils import Markup as Markup, contextfunction as contextfunction, import_string as import_string
from _typeshed import Incomplete
from collections.abc import Generator

GETTEXT_FUNCTIONS: Incomplete

class ExtensionRegistry(type):
    def __new__(cls, name, bases, d): ...

class Extension(Incomplete):
    tags: Incomplete
    priority: int
    environment: Incomplete
    def __init__(self, environment) -> None: ...
    def bind(self, environment): ...
    def preprocess(self, source, name, filename: Incomplete | None = None): ...
    def filter_stream(self, stream): ...
    def parse(self, parser) -> None: ...
    def attr(self, name, lineno: Incomplete | None = None): ...
    def call_method(self, name, args: Incomplete | None = None, kwargs: Incomplete | None = None, dyn_args: Incomplete | None = None, dyn_kwargs: Incomplete | None = None, lineno: Incomplete | None = None): ...

class InternationalizationExtension(Extension):
    tags: Incomplete
    def __init__(self, environment) -> None: ...
    def parse(self, parser): ...

class ExprStmtExtension(Extension):
    tags: Incomplete
    def parse(self, parser): ...

class LoopControlExtension(Extension):
    tags: Incomplete
    def parse(self, parser): ...

class WithExtension(Extension): ...
class AutoEscapeExtension(Extension): ...

def extract_from_ast(node, gettext_functions=..., babel_style: bool = True) -> Generator[Incomplete]: ...

class _CommentFinder:
    tokens: Incomplete
    comment_tags: Incomplete
    offset: int
    last_lineno: int
    def __init__(self, tokens, comment_tags) -> None: ...
    def find_backwards(self, offset): ...
    def find_comments(self, lineno): ...

def babel_extract(fileobj, keywords, comment_tags, options) -> Generator[Incomplete, None, Incomplete]: ...
i18n = InternationalizationExtension
do = ExprStmtExtension
loopcontrols = LoopControlExtension
with_ = WithExtension
autoescape = AutoEscapeExtension
