from . import nodes as nodes
from ._compat import iteritems as iteritems, string_types as string_types
from .compiler import CodeGenerator as CodeGenerator
from _typeshed import Incomplete
from collections.abc import Generator

class TrackingCodeGenerator(CodeGenerator):
    undeclared_identifiers: Incomplete
    def __init__(self, environment) -> None: ...
    def write(self, x) -> None: ...
    def enter_frame(self, frame) -> None: ...

def find_undeclared_variables(ast): ...
def find_referenced_templates(ast) -> Generator[Incomplete]: ...
