from ._compat import integer_types as integer_types, string_types as string_types, text_type as text_type
from .runtime import Undefined as Undefined
from _typeshed import Incomplete

number_re: Incomplete
regex_type: Incomplete
test_callable = callable

def test_odd(value): ...
def test_even(value): ...
def test_divisibleby(value, num): ...
def test_defined(value): ...
def test_undefined(value): ...
def test_none(value): ...
def test_lower(value): ...
def test_upper(value): ...
def test_string(value): ...
def test_mapping(value): ...
def test_number(value): ...
def test_sequence(value): ...
def test_sameas(value, other): ...
def test_iterable(value): ...
def test_escaped(value): ...
def test_in(value, seq): ...

TESTS: Incomplete
