from .nodes import Node as Node

class NodeVisitor:
    def get_visitor(self, node): ...
    def visit(self, node, *args, **kwargs): ...
    def generic_visit(self, node, *args, **kwargs) -> None: ...

class NodeTransformer(NodeVisitor):
    def generic_visit(self, node, *args, **kwargs): ...
    def visit_list(self, node, *args, **kwargs): ...
