# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python

on:
  push:
    branches:
      - '**'
    paths:
      - '.github/workflows/python.yml'
      - '**.py'
      - '**.pyi'
  pull_request:
    branches:
      - '**'
    paths:
      - '.github/workflows/python.yml'
      - '**.py'
      - '**.pyi'

jobs:
  job_lint:
    name: ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: ['ubuntu-latest']
        python-version: ['3.8']

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Do linting
        run: |
          make check
