from . import util as util
from ..markdown import Extension as Extension
from ..markdown.postprocessors import Postprocessor as Postprocessor
from _typeshed import Incomplete

RE_TAG_HTML: str
RE_TAG_LINK_ATTR: Incomplete

def repl_relative(m, base_path, relative_path): ...
def repl_absolute(m, base_path): ...
def repl(m, base_path, rel_path: Incomplete | None = None): ...

class PathConverterPostprocessor(Postprocessor):
    def run(self, text): ...

class PathConverterExtension(Extension):
    config: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    def extendMarkdown(self, md) -> None: ...

def makeExtension(*args, **kwargs): ...
