from _typeshed import Incomplete
from typing import NamedTuple

__all__ = ['Pep562']

class Version(NamedTuple('Version', [('major', Incomplete), ('minor', Incomplete), ('micro', Incomplete), ('release', Incomplete), ('pre', Incomplete), ('post', Incomplete), ('dev', Incomplete)])):
    def __new__(cls, major, minor, micro, release: str = 'final', pre: int = 0, post: int = 0, dev: int = 0): ...

class Pep562:
    def __init__(self, name) -> None: ...
    def __dir__(self): ...
    def __getattr__(self, name): ...
