from _typeshed import Incomplete

RE_TAGS: Incomplete
RE_INVALID_SLUG_CHAR: Incomplete
RE_SEP: Incomplete
RE_ASCII_LETTERS: Incomplete
NO_CASED: int
UNICODE_CASED: int
CASED: int

def uslugify(text, sep, cased=..., percent_encode: bool = False): ...
def uslugify_encoded(text, sep): ...
def uslugify_cased(text, sep): ...
def uslugify_cased_encoded(text, sep): ...
def gfm(text, sep): ...
def gfm_encoded(text, sep): ...
