from ..markdown import Extension as Extension
from ..markdown.blockprocessors import BlockProcessor as BlockProcessor
from _typeshed import Incomplete

class TabbedProcessor(BlockProcessor):
    START: Incomplete
    COMPRESS_SPACES: Incomplete
    tab_group_count: int
    current_sibling: Incomplete
    content_indention: int
    def __init__(self, *args) -> None: ...
    content_indent: int
    def get_sibling(self, parent, block): ...
    def test(self, parent, block): ...
    def run(self, parent, blocks) -> None: ...

class TabbedExtension(Extension):
    tab_processor: Incomplete
    def extendMarkdown(self, md) -> None: ...
    def reset(self) -> None: ...

def makeExtension(*args, **kwargs): ...
