from ..markdown import Extension as Extension
from ..markdown.treeprocessors import Treeprocessor as Treeprocessor
from _typeshed import Incomplete

RE_CHECKBOX: Incomplete

def get_checkbox(state, custom_checkbox: bool = False, clickable_checkbox: bool = False): ...

class TasklistTreeprocessor(Treeprocessor):
    def __init__(self, md) -> None: ...
    def inline(self, li): ...
    def sub_paragraph(self, li): ...
    custom_checkbox: Incomplete
    clickable_checkbox: Incomplete
    def run(self, root): ...

class TasklistExtension(Extension):
    config: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    def extendMarkdown(self, md) -> None: ...

def makeExtension(*args, **kwargs): ...
