from ..markdown.inlinepatterns import InlineProcessor as InlineProcessor
from _typeshed import Incomplete
from typing import NamedTuple

html_parser: Incomplete
RE_WIN_DRIVE_LETTER: Incomplete
RE_WIN_DRIVE_PATH: Incomplete
RE_URL: Incomplete
RE_WIN_DEFAULT_PROTOCOL: Incomplete

def is_win(): ...
def is_linux(): ...
def is_mac(): ...
def url2path(path): ...
def path2url(url): ...
def get_code_points(s): ...
def get_ord(c): ...
def get_char(value): ...
def escape_chars(md, echrs) -> None: ...
def parse_url(url): ...

class PatSeqItem(NamedTuple('PatSeqItem', [('pattern', Incomplete), ('builder', Incomplete), ('tags', Incomplete)])): ...

class PatternSequenceProcessor(InlineProcessor):
    PATTERNS: Incomplete
    def build_single(self, m, tag, idx): ...
    def build_double(self, m, tags, idx): ...
    def build_double2(self, m, tags, idx): ...
    def parse_sub_patterns(self, data, parent, last, idx) -> None: ...
    def build_element(self, m, builder, tags, index): ...
    def handleMatch(self, m, data): ...

class PymdownxDeprecationWarning(UserWarning): ...
